# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from terrasentia_sensors/FourWD.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import terrasentia_sensors.msg

class FourWD(genpy.Message):
  _md5sum = "039fc197805f8cfb1c0f73e3c46ee368"
  _type = "terrasentia_sensors/FourWD"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
terrasentia_sensors/Motor front_left
terrasentia_sensors/Motor front_right
terrasentia_sensors/Motor back_left
terrasentia_sensors/Motor back_right
float32 read_timestamp

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: terrasentia_sensors/Motor
bool status
float32 current
float32 linear_speed"""
  __slots__ = ['header','front_left','front_right','back_left','back_right','read_timestamp']
  _slot_types = ['std_msgs/Header','terrasentia_sensors/Motor','terrasentia_sensors/Motor','terrasentia_sensors/Motor','terrasentia_sensors/Motor','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,front_left,front_right,back_left,back_right,read_timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FourWD, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.front_left is None:
        self.front_left = terrasentia_sensors.msg.Motor()
      if self.front_right is None:
        self.front_right = terrasentia_sensors.msg.Motor()
      if self.back_left is None:
        self.back_left = terrasentia_sensors.msg.Motor()
      if self.back_right is None:
        self.back_right = terrasentia_sensors.msg.Motor()
      if self.read_timestamp is None:
        self.read_timestamp = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.front_left = terrasentia_sensors.msg.Motor()
      self.front_right = terrasentia_sensors.msg.Motor()
      self.back_left = terrasentia_sensors.msg.Motor()
      self.back_right = terrasentia_sensors.msg.Motor()
      self.read_timestamp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2fB2fB2fB3f().pack(_x.front_left.status, _x.front_left.current, _x.front_left.linear_speed, _x.front_right.status, _x.front_right.current, _x.front_right.linear_speed, _x.back_left.status, _x.back_left.current, _x.back_left.linear_speed, _x.back_right.status, _x.back_right.current, _x.back_right.linear_speed, _x.read_timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.front_left is None:
        self.front_left = terrasentia_sensors.msg.Motor()
      if self.front_right is None:
        self.front_right = terrasentia_sensors.msg.Motor()
      if self.back_left is None:
        self.back_left = terrasentia_sensors.msg.Motor()
      if self.back_right is None:
        self.back_right = terrasentia_sensors.msg.Motor()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.front_left.status, _x.front_left.current, _x.front_left.linear_speed, _x.front_right.status, _x.front_right.current, _x.front_right.linear_speed, _x.back_left.status, _x.back_left.current, _x.back_left.linear_speed, _x.back_right.status, _x.back_right.current, _x.back_right.linear_speed, _x.read_timestamp,) = _get_struct_B2fB2fB2fB3f().unpack(str[start:end])
      self.front_left.status = bool(self.front_left.status)
      self.front_right.status = bool(self.front_right.status)
      self.back_left.status = bool(self.back_left.status)
      self.back_right.status = bool(self.back_right.status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2fB2fB2fB3f().pack(_x.front_left.status, _x.front_left.current, _x.front_left.linear_speed, _x.front_right.status, _x.front_right.current, _x.front_right.linear_speed, _x.back_left.status, _x.back_left.current, _x.back_left.linear_speed, _x.back_right.status, _x.back_right.current, _x.back_right.linear_speed, _x.read_timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.front_left is None:
        self.front_left = terrasentia_sensors.msg.Motor()
      if self.front_right is None:
        self.front_right = terrasentia_sensors.msg.Motor()
      if self.back_left is None:
        self.back_left = terrasentia_sensors.msg.Motor()
      if self.back_right is None:
        self.back_right = terrasentia_sensors.msg.Motor()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.front_left.status, _x.front_left.current, _x.front_left.linear_speed, _x.front_right.status, _x.front_right.current, _x.front_right.linear_speed, _x.back_left.status, _x.back_left.current, _x.back_left.linear_speed, _x.back_right.status, _x.back_right.current, _x.back_right.linear_speed, _x.read_timestamp,) = _get_struct_B2fB2fB2fB3f().unpack(str[start:end])
      self.front_left.status = bool(self.front_left.status)
      self.front_right.status = bool(self.front_right.status)
      self.back_left.status = bool(self.back_left.status)
      self.back_right.status = bool(self.back_right.status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B2fB2fB2fB3f = None
def _get_struct_B2fB2fB2fB3f():
    global _struct_B2fB2fB2fB3f
    if _struct_B2fB2fB2fB3f is None:
        _struct_B2fB2fB2fB3f = struct.Struct("<B2fB2fB2fB3f")
    return _struct_B2fB2fB2fB3f
