# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from terrasentia_sensors/TerraGps.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import terrasentia_sensors.msg

class TerraGps(genpy.Message):
  _md5sum = "b34d8639cf3adf476f2bee63f46d8e96"
  _type = "terrasentia_sensors/TerraGps"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 time
float64 latitude
float64 longitude
float64 altitude
float64 reference_latitude
float64 reference_longitude
float64 reference_altitude
float64 reference_heading
XYZ_Base velocity
XYZ_Base covariance
uint8 covariance_type
uint16 service
int8 status

================================================================================
MSG: terrasentia_sensors/XYZ_Base
float64 x
float64 y
float64 z
"""
  __slots__ = ['time','latitude','longitude','altitude','reference_latitude','reference_longitude','reference_altitude','reference_heading','velocity','covariance','covariance_type','service','status']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','terrasentia_sensors/XYZ_Base','terrasentia_sensors/XYZ_Base','uint8','uint16','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,latitude,longitude,altitude,reference_latitude,reference_longitude,reference_altitude,reference_heading,velocity,covariance,covariance_type,service,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TerraGps, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.reference_latitude is None:
        self.reference_latitude = 0.
      if self.reference_longitude is None:
        self.reference_longitude = 0.
      if self.reference_altitude is None:
        self.reference_altitude = 0.
      if self.reference_heading is None:
        self.reference_heading = 0.
      if self.velocity is None:
        self.velocity = terrasentia_sensors.msg.XYZ_Base()
      if self.covariance is None:
        self.covariance = terrasentia_sensors.msg.XYZ_Base()
      if self.covariance_type is None:
        self.covariance_type = 0
      if self.service is None:
        self.service = 0
      if self.status is None:
        self.status = 0
    else:
      self.time = 0.
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.
      self.reference_latitude = 0.
      self.reference_longitude = 0.
      self.reference_altitude = 0.
      self.reference_heading = 0.
      self.velocity = terrasentia_sensors.msg.XYZ_Base()
      self.covariance = terrasentia_sensors.msg.XYZ_Base()
      self.covariance_type = 0
      self.service = 0
      self.status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_14dBHb().pack(_x.time, _x.latitude, _x.longitude, _x.altitude, _x.reference_latitude, _x.reference_longitude, _x.reference_altitude, _x.reference_heading, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.covariance_type, _x.service, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.velocity is None:
        self.velocity = terrasentia_sensors.msg.XYZ_Base()
      if self.covariance is None:
        self.covariance = terrasentia_sensors.msg.XYZ_Base()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.time, _x.latitude, _x.longitude, _x.altitude, _x.reference_latitude, _x.reference_longitude, _x.reference_altitude, _x.reference_heading, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.covariance_type, _x.service, _x.status,) = _get_struct_14dBHb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_14dBHb().pack(_x.time, _x.latitude, _x.longitude, _x.altitude, _x.reference_latitude, _x.reference_longitude, _x.reference_altitude, _x.reference_heading, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.covariance_type, _x.service, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.velocity is None:
        self.velocity = terrasentia_sensors.msg.XYZ_Base()
      if self.covariance is None:
        self.covariance = terrasentia_sensors.msg.XYZ_Base()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.time, _x.latitude, _x.longitude, _x.altitude, _x.reference_latitude, _x.reference_longitude, _x.reference_altitude, _x.reference_heading, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.covariance_type, _x.service, _x.status,) = _get_struct_14dBHb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14dBHb = None
def _get_struct_14dBHb():
    global _struct_14dBHb
    if _struct_14dBHb is None:
        _struct_14dBHb = struct.Struct("<14dBHb")
    return _struct_14dBHb
