// Generated by gencpp from file terrasentia_sensors/FourWD.msg
// DO NOT EDIT!


#ifndef TERRASENTIA_SENSORS_MESSAGE_FOURWD_H
#define TERRASENTIA_SENSORS_MESSAGE_FOURWD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <terrasentia_sensors/Motor.h>
#include <terrasentia_sensors/Motor.h>
#include <terrasentia_sensors/Motor.h>
#include <terrasentia_sensors/Motor.h>

namespace terrasentia_sensors
{
template <class ContainerAllocator>
struct FourWD_
{
  typedef FourWD_<ContainerAllocator> Type;

  FourWD_()
    : header()
    , front_left()
    , front_right()
    , back_left()
    , back_right()
    , read_timestamp(0.0)  {
    }
  FourWD_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , front_left(_alloc)
    , front_right(_alloc)
    , back_left(_alloc)
    , back_right(_alloc)
    , read_timestamp(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::terrasentia_sensors::Motor_<ContainerAllocator>  _front_left_type;
  _front_left_type front_left;

   typedef  ::terrasentia_sensors::Motor_<ContainerAllocator>  _front_right_type;
  _front_right_type front_right;

   typedef  ::terrasentia_sensors::Motor_<ContainerAllocator>  _back_left_type;
  _back_left_type back_left;

   typedef  ::terrasentia_sensors::Motor_<ContainerAllocator>  _back_right_type;
  _back_right_type back_right;

   typedef float _read_timestamp_type;
  _read_timestamp_type read_timestamp;





  typedef boost::shared_ptr< ::terrasentia_sensors::FourWD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::terrasentia_sensors::FourWD_<ContainerAllocator> const> ConstPtr;

}; // struct FourWD_

typedef ::terrasentia_sensors::FourWD_<std::allocator<void> > FourWD;

typedef boost::shared_ptr< ::terrasentia_sensors::FourWD > FourWDPtr;
typedef boost::shared_ptr< ::terrasentia_sensors::FourWD const> FourWDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::terrasentia_sensors::FourWD_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::terrasentia_sensors::FourWD_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::terrasentia_sensors::FourWD_<ContainerAllocator1> & lhs, const ::terrasentia_sensors::FourWD_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.front_left == rhs.front_left &&
    lhs.front_right == rhs.front_right &&
    lhs.back_left == rhs.back_left &&
    lhs.back_right == rhs.back_right &&
    lhs.read_timestamp == rhs.read_timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::terrasentia_sensors::FourWD_<ContainerAllocator1> & lhs, const ::terrasentia_sensors::FourWD_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace terrasentia_sensors

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::terrasentia_sensors::FourWD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::terrasentia_sensors::FourWD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::terrasentia_sensors::FourWD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::terrasentia_sensors::FourWD_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::terrasentia_sensors::FourWD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::terrasentia_sensors::FourWD_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::terrasentia_sensors::FourWD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "039fc197805f8cfb1c0f73e3c46ee368";
  }

  static const char* value(const ::terrasentia_sensors::FourWD_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x039fc197805f8cfbULL;
  static const uint64_t static_value2 = 0x1c0f73e3c46ee368ULL;
};

template<class ContainerAllocator>
struct DataType< ::terrasentia_sensors::FourWD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "terrasentia_sensors/FourWD";
  }

  static const char* value(const ::terrasentia_sensors::FourWD_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::terrasentia_sensors::FourWD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"terrasentia_sensors/Motor front_left\n"
"terrasentia_sensors/Motor front_right\n"
"terrasentia_sensors/Motor back_left\n"
"terrasentia_sensors/Motor back_right\n"
"float32 read_timestamp\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: terrasentia_sensors/Motor\n"
"bool status\n"
"float32 current\n"
"float32 linear_speed\n"
;
  }

  static const char* value(const ::terrasentia_sensors::FourWD_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::terrasentia_sensors::FourWD_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.front_left);
      stream.next(m.front_right);
      stream.next(m.back_left);
      stream.next(m.back_right);
      stream.next(m.read_timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FourWD_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::terrasentia_sensors::FourWD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::terrasentia_sensors::FourWD_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "front_left: ";
    s << std::endl;
    Printer< ::terrasentia_sensors::Motor_<ContainerAllocator> >::stream(s, indent + "  ", v.front_left);
    s << indent << "front_right: ";
    s << std::endl;
    Printer< ::terrasentia_sensors::Motor_<ContainerAllocator> >::stream(s, indent + "  ", v.front_right);
    s << indent << "back_left: ";
    s << std::endl;
    Printer< ::terrasentia_sensors::Motor_<ContainerAllocator> >::stream(s, indent + "  ", v.back_left);
    s << indent << "back_right: ";
    s << std::endl;
    Printer< ::terrasentia_sensors::Motor_<ContainerAllocator> >::stream(s, indent + "  ", v.back_right);
    s << indent << "read_timestamp: ";
    Printer<float>::stream(s, indent + "  ", v.read_timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TERRASENTIA_SENSORS_MESSAGE_FOURWD_H
