// Generated by gencpp from file terrasentia_sensors/TerraBattery.msg
// DO NOT EDIT!


#ifndef TERRASENTIA_SENSORS_MESSAGE_TERRABATTERY_H
#define TERRASENTIA_SENSORS_MESSAGE_TERRABATTERY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace terrasentia_sensors
{
template <class ContainerAllocator>
struct TerraBattery_
{
  typedef TerraBattery_<ContainerAllocator> Type;

  TerraBattery_()
    : stamp()
    , voltage(0.0)
    , vmax(0.0)
    , vmin(0.0)  {
    }
  TerraBattery_(const ContainerAllocator& _alloc)
    : stamp()
    , voltage(0.0)
    , vmax(0.0)
    , vmin(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef double _voltage_type;
  _voltage_type voltage;

   typedef double _vmax_type;
  _vmax_type vmax;

   typedef double _vmin_type;
  _vmin_type vmin;





  typedef boost::shared_ptr< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> const> ConstPtr;

}; // struct TerraBattery_

typedef ::terrasentia_sensors::TerraBattery_<std::allocator<void> > TerraBattery;

typedef boost::shared_ptr< ::terrasentia_sensors::TerraBattery > TerraBatteryPtr;
typedef boost::shared_ptr< ::terrasentia_sensors::TerraBattery const> TerraBatteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::terrasentia_sensors::TerraBattery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::terrasentia_sensors::TerraBattery_<ContainerAllocator1> & lhs, const ::terrasentia_sensors::TerraBattery_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.voltage == rhs.voltage &&
    lhs.vmax == rhs.vmax &&
    lhs.vmin == rhs.vmin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::terrasentia_sensors::TerraBattery_<ContainerAllocator1> & lhs, const ::terrasentia_sensors::TerraBattery_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace terrasentia_sensors

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a9bbba12ac00a99cf3603ae02c56555";
  }

  static const char* value(const ::terrasentia_sensors::TerraBattery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a9bbba12ac00a99ULL;
  static const uint64_t static_value2 = 0xcf3603ae02c56555ULL;
};

template<class ContainerAllocator>
struct DataType< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "terrasentia_sensors/TerraBattery";
  }

  static const char* value(const ::terrasentia_sensors::TerraBattery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float64 voltage\n"
"float64 vmax\n"
"float64 vmin\n"
;
  }

  static const char* value(const ::terrasentia_sensors::TerraBattery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.voltage);
      stream.next(m.vmax);
      stream.next(m.vmin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TerraBattery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::terrasentia_sensors::TerraBattery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::terrasentia_sensors::TerraBattery_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    s << indent << "vmax: ";
    Printer<double>::stream(s, indent + "  ", v.vmax);
    s << indent << "vmin: ";
    Printer<double>::stream(s, indent + "  ", v.vmin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TERRASENTIA_SENSORS_MESSAGE_TERRABATTERY_H
